env:
    domain: "rehab.vagrant.local"
    ip: "192.168.33.10"
    ram: 512
    vbname: "Appengine Project"
database:
    name: "appengine-database"
    user: "appengine-user"
    pass: "appengine-password"
